In [263]:
import numpy as np

In [264]:
import torch

In [265]:
x = torch.FloatTensor([[1,2,3,4,5,6,7],[3,5,6,7,8,4,5]])
x

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [3., 5., 6., 7., 8., 4., 5.]])

In [4]:
x.unfold(0,2,2)

tensor([[[1., 3.],
         [2., 5.],
         [3., 6.],
         [4., 7.],
         [5., 8.],
         [6., 4.],
         [7., 5.]]])

In [5]:
mock_filter_1 = torch.tensor([[1.0,2,1],[2,4,5],[6,7,8]])
mock_filter_2 = torch.tensor([[1.0,6,7],[1,9,5],[4,7,8]])
mock_filter_3 = torch.tensor([[1.0,3,1],[7,0,5],[9,7,0]])
mock_filter_4 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])

In [6]:
mock_filter_combined = torch.stack([mock_filter_1, mock_filter_2, mock_filter_3, mock_filter_4]) 

In [7]:
mock_filter_combined = torch.stack([mock_filter_combined, mock_filter_combined], dim=1)

In [8]:
mock_filter_combined.shape

torch.Size([4, 2, 3, 3])

In [9]:
print(mock_filter_combined[0])
print(mock_filter_combined[1])
print(mock_filter_combined[2])
print(mock_filter_combined[3])

tensor([[[1., 2., 1.],
         [2., 4., 5.],
         [6., 7., 8.]],

        [[1., 2., 1.],
         [2., 4., 5.],
         [6., 7., 8.]]])
tensor([[[1., 6., 7.],
         [1., 9., 5.],
         [4., 7., 8.]],

        [[1., 6., 7.],
         [1., 9., 5.],
         [4., 7., 8.]]])
tensor([[[1., 3., 1.],
         [7., 0., 5.],
         [9., 7., 0.]],

        [[1., 3., 1.],
         [7., 0., 5.],
         [9., 7., 0.]]])
tensor([[[3., 2., 4.],
         [0., 4., 5.],
         [1., 7., 0.]],

        [[3., 2., 4.],
         [0., 4., 5.],
         [1., 7., 0.]]])


In [10]:
filter_groups = mock_filter_combined.unfold(0, 2, 2)

In [11]:
filter_groups.shape

torch.Size([2, 2, 3, 3, 2])

In [12]:
filter_groups[0].permute(3,0,1,2)

tensor([[[[1., 2., 1.],
          [2., 4., 5.],
          [6., 7., 8.]],

         [[1., 2., 1.],
          [2., 4., 5.],
          [6., 7., 8.]]],


        [[[1., 6., 7.],
          [1., 9., 5.],
          [4., 7., 8.]],

         [[1., 6., 7.],
          [1., 9., 5.],
          [4., 7., 8.]]]])

In [13]:
filter_groups[1].permute(3,0,1,2)

tensor([[[[1., 3., 1.],
          [7., 0., 5.],
          [9., 7., 0.]],

         [[1., 3., 1.],
          [7., 0., 5.],
          [9., 7., 0.]]],


        [[[3., 2., 4.],
          [0., 4., 5.],
          [1., 7., 0.]],

         [[3., 2., 4.],
          [0., 4., 5.],
          [1., 7., 0.]]]])

### Testing the activations

In [266]:
import torch.nn.functional as F

In [267]:
filters = mock_filter_combined
filters.shape

torch.Size([5, 2, 3, 3])

In [268]:
inputs = torch.randn(2,2,4,4)

In [269]:
activations = F.conv2d(inputs,filters)

In [270]:
activations.shape

torch.Size([2, 5, 2, 2])

In [19]:
inputs

tensor([[[[-0.9836, -1.4208, -0.8229, -0.5846],
          [ 0.3779,  0.3007,  0.0868, -1.5526],
          [-0.8341,  0.4526,  0.9579,  0.3471],
          [ 0.0823,  0.2645, -0.3746, -1.2217]],

         [[ 0.6883,  0.5724, -0.0845, -0.0906],
          [ 0.9938,  0.0661,  1.9325,  1.6026],
          [-0.4197, -0.7367, -1.0242, -0.8743],
          [ 0.6043,  0.4772,  1.5056, -1.1296]]],


        [[[-0.5626,  0.3638, -0.5997, -1.6459],
          [-0.3427, -0.3129,  0.9347,  1.5927],
          [ 0.8174, -0.1902,  0.7727, -0.5489],
          [-0.8904,  1.3198, -2.2056, -1.1502]],

         [[ 0.7915,  1.2240, -0.2449, -0.9252],
          [ 1.0592, -0.5847, -0.5430,  0.6257],
          [ 0.1448,  0.0330, -1.5823,  0.4018],
          [-2.8942, -0.0568,  1.1775, -0.7728]]]])

In [20]:
activations

tensor([[[[  1.3666,  -0.6625],
          [ 18.5080,  -5.4578]],

         [[ -4.5010,   1.9549],
          [ 30.5517,   1.3895]],

         [[  2.6776,  -4.4479],
          [  6.7547,  16.4415]],

         [[  2.1093,   0.5193],
          [ 17.3366,  11.0968]]],


        [[[  0.5576,   0.4039],
          [-25.5301, -17.1863]],

         [[ -5.2884, -15.2308],
          [-20.9491,  -8.7257]],

         [[ 18.6822,  -5.7908],
          [-24.1178,   4.8312]],

         [[ -1.2860,  -0.3757],
          [  2.3012,  -2.9430]]]])

In [21]:
groups = torch.split(activations, 2, dim=1)

In [22]:
groups

(tensor([[[[  1.3666,  -0.6625],
           [ 18.5080,  -5.4578]],
 
          [[ -4.5010,   1.9549],
           [ 30.5517,   1.3895]]],
 
 
         [[[  0.5576,   0.4039],
           [-25.5301, -17.1863]],
 
          [[ -5.2884, -15.2308],
           [-20.9491,  -8.7257]]]]), tensor([[[[  2.6776,  -4.4479],
           [  6.7547,  16.4415]],
 
          [[  2.1093,   0.5193],
           [ 17.3366,  11.0968]]],
 
 
         [[[ 18.6822,  -5.7908],
           [-24.1178,   4.8312]],
 
          [[ -1.2860,  -0.3757],
           [  2.3012,  -2.9430]]]]))

In [23]:
groups[0]

tensor([[[[  1.3666,  -0.6625],
          [ 18.5080,  -5.4578]],

         [[ -4.5010,   1.9549],
          [ 30.5517,   1.3895]]],


        [[[  0.5576,   0.4039],
          [-25.5301, -17.1863]],

         [[ -5.2884, -15.2308],
          [-20.9491,  -8.7257]]]])

### Another test case where filtere are not divisible by the number of groups

In [283]:
mock_filter_1 = torch.tensor([[1.0,2,1],[2,4,5],[6,7,8]])
mock_filter_2 = torch.tensor([[1.0,6,7],[1,9,5],[4,7,8]])
mock_filter_3 = torch.tensor([[1.0,3,1],[7,0,5],[9,7,0]])
mock_filter_4 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])
mock_filter_5 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])
mock_filter_6 = torch.tensor([[3.0,2,5],[1,8,0],[2,5,8]])
mock_filter_7 = torch.tensor([[4.0,6,9],[0,0,5],[1,3,7]])

In [285]:
mock_filter_combined = torch.stack([mock_filter_1, mock_filter_2, mock_filter_3, mock_filter_4,mock_filter_5,
                                   mock_filter_6, mock_filter_7]) 

In [286]:
mock_filter_combined = torch.stack([mock_filter_combined, mock_filter_combined], dim=1)
mock_filter_combined.shape

torch.Size([7, 2, 3, 3])

In [287]:
inputs = torch.randn(2,2,4,4)

In [288]:
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([2, 7, 2, 2])

In [276]:
inputs

tensor([[[[ 2.3622, -1.1286,  1.4443,  1.5417],
          [ 0.5551,  0.1916,  0.8698, -0.7866],
          [-0.2852, -1.0119, -0.8040,  1.5948],
          [-0.4591,  0.5299,  0.0097,  0.1706]],

         [[-0.7976, -0.2607, -0.3897,  0.2649],
          [-0.7505, -1.4881, -1.4529,  0.5981],
          [-0.3706,  1.8126,  0.8463, -0.2696],
          [-1.1173,  0.5162,  0.2351, -0.2540]]],


        [[[-0.8320, -0.5499,  0.2469,  1.2087],
          [-0.7836, -0.1427, -0.4933, -0.0644],
          [ 0.8549,  0.6271,  1.7209,  0.9265],
          [-0.6241, -0.5344,  2.8096, -0.7579]],

         [[-0.7587,  1.3482,  1.2846,  0.8260],
          [ 0.1844,  2.2469, -0.0652,  1.3340],
          [ 0.1579,  0.7577,  0.1223,  0.5710],
          [ 0.5782,  0.0561,  1.0526, -0.4175]]]])

In [277]:
activations

tensor([[[[ -6.6427,  12.3607],
          [ -1.4465,  13.0683]],

         [[-10.8479,  24.1984],
          [ -2.3186,   6.9239]],

         [[ -6.1294,   1.0663],
          [-15.9124,  20.1248]],

         [[  2.9815,   2.9900],
          [  3.6491,   3.7449]],

         [[  2.9815,   2.9900],
          [  3.6491,   3.7449]]],


        [[[ 36.4793,  47.4099],
          [ 47.1064,  34.6501]],

         [[ 57.9563,  58.0776],
          [ 58.1759,  48.8213]],

         [[ 14.1579,  53.8710],
          [ 17.6990,  41.6117]],

         [[ 19.2819,  31.9977],
          [ 11.5384,  51.6920]],

         [[ 19.2819,  31.9977],
          [ 11.5384,  51.6920]]]])

In [278]:
groups = torch.split(activations, 2, dim=1)
list(groups)

[tensor([[[[ -6.6427,  12.3607],
           [ -1.4465,  13.0683]],
 
          [[-10.8479,  24.1984],
           [ -2.3186,   6.9239]]],
 
 
         [[[ 36.4793,  47.4099],
           [ 47.1064,  34.6501]],
 
          [[ 57.9563,  58.0776],
           [ 58.1759,  48.8213]]]]), tensor([[[[ -6.1294,   1.0663],
           [-15.9124,  20.1248]],
 
          [[  2.9815,   2.9900],
           [  3.6491,   3.7449]]],
 
 
         [[[ 14.1579,  53.8710],
           [ 17.6990,  41.6117]],
 
          [[ 19.2819,  31.9977],
           [ 11.5384,  51.6920]]]]), tensor([[[[ 2.9815,  2.9900],
           [ 3.6491,  3.7449]]],
 
 
         [[[19.2819, 31.9977],
           [11.5384, 51.6920]]]])]

In [32]:
groupwise_mean = [torch.mean(groups[i]) for i in range(0,2)]

In [33]:
groupwise_mean

[tensor(-5.7747), tensor(-5.1012)]

In [34]:
groupwise_std = [torch.std(groups[i]) for i in range(0,2)]
groupwise_std

[tensor(9.2109), tensor(11.2790)]

### Test channelwise receptive field calcualtions

In [35]:
def calculate_receptive_field_layer_no_batch_norm(feature_maps, linear_map_param_1, 
                                                  linear_map_param_2):
    number_of_maps = feature_maps[1]
    std_map_wise = feature_maps.transpose(0,1).contiguous().view(number_of_maps, -1).std(1)
    receptive_fields = feature_maps.transpose(1,3).div(std_map_wise).transpose(1,3)
    receptive_fields = torch.sigmoid(linear_map_param_1 * receptive_fields + linear_map_param_2)
    return receptive_fields

In [36]:
calculate_receptive_field_layer_no_batch_norm(activations)
print(activations.shape)

TypeError: calculate_receptive_field_layer_no_batch_norm() missing 2 required positional arguments: 'linear_map_param_1' and 'linear_map_param_2'

In [37]:
kk=activations.transpose(0,1)
print(kk.shape)
c =kk.contiguous().view(5, -1)

torch.Size([5, 2, 2, 2])


In [38]:
c.shape

torch.Size([5, 8])

In [39]:
B = torch.mean(c,1)
c.std(1)

tensor([ 5.8490, 11.3524, 12.9333, 10.2226, 10.2226])

In [40]:
print(activations)
print(activations.shape)

tensor([[[[  2.0685,   0.2549],
          [ -6.9292,  -8.5334]],

         [[ -0.4534, -15.2564],
          [-17.1740, -25.8676]],

         [[-15.4725,   6.7212],
          [-10.5295, -13.0490]],

         [[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]],

         [[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[ -0.3115,   2.5259],
          [  0.8470, -13.2290]],

         [[  8.1133,  -7.0418],
          [  2.0821, -13.4903]],

         [[-16.0950,   6.6377],
          [ 17.8532, -12.0492]],

         [[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]],

         [[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]])
torch.Size([2, 5, 2, 2])


In [41]:
kk=activations.transpose(1,3)
print(kk)
print(kk.shape)
activations.transpose(1,3).div(torch.Tensor([0.1,1,1,1,1])).transpose(1,3)

tensor([[[[  2.0685,  -0.4534, -15.4725,  -7.3777,  -7.3777],
          [ -6.9292, -17.1740, -10.5295, -17.8959, -17.8959]],

         [[  0.2549, -15.2564,   6.7212, -14.0625, -14.0625],
          [ -8.5334, -25.8676, -13.0490,  -1.4268,  -1.4268]]],


        [[[ -0.3115,   8.1133, -16.0950,  15.8582,  15.8582],
          [  0.8470,   2.0821,  17.8532,  -6.1312,  -6.1312]],

         [[  2.5259,  -7.0418,   6.6377,  -4.0069,  -4.0069],
          [-13.2290, -13.4903, -12.0492, -10.5940, -10.5940]]]])
torch.Size([2, 2, 2, 5])


tensor([[[[  20.6849,    2.5488],
          [ -69.2920,  -85.3340]],

         [[  -0.4534,  -15.2564],
          [ -17.1740,  -25.8676]],

         [[ -15.4725,    6.7212],
          [ -10.5295,  -13.0490]],

         [[  -7.3777,  -14.0625],
          [ -17.8959,   -1.4268]],

         [[  -7.3777,  -14.0625],
          [ -17.8959,   -1.4268]]],


        [[[  -3.1153,   25.2586],
          [   8.4701, -132.2896]],

         [[   8.1133,   -7.0418],
          [   2.0821,  -13.4903]],

         [[ -16.0950,    6.6377],
          [  17.8532,  -12.0492]],

         [[  15.8582,   -4.0069],
          [  -6.1312,  -10.5940]],

         [[  15.8582,   -4.0069],
          [  -6.1312,  -10.5940]]]])

In [42]:
receptive_fields = 2.0 * activations + 1.0
print(receptive_fields)

tensor([[[[  5.1370,   1.5098],
          [-12.8584, -16.0668]],

         [[  0.0933, -29.5128],
          [-33.3480, -50.7352]],

         [[-29.9450,  14.4424],
          [-20.0589, -25.0981]],

         [[-13.7555, -27.1251],
          [-34.7918,  -1.8537]],

         [[-13.7555, -27.1251],
          [-34.7918,  -1.8537]]],


        [[[  0.3769,   6.0517],
          [  2.6940, -25.4579]],

         [[ 17.2266, -13.0835],
          [  5.1642, -25.9807]],

         [[-31.1900,  14.2754],
          [ 36.7064, -23.0984]],

         [[ 32.7163,  -7.0137],
          [-11.2623, -20.1880]],

         [[ 32.7163,  -7.0137],
          [-11.2623, -20.1880]]]])


In [43]:
receptive_fields = torch.sigmoid(receptive_fields)
print(receptive_fields)

tensor([[[[9.9416e-01, 8.1903e-01],
          [2.6041e-06, 1.0526e-07]],

         [[5.2330e-01, 1.5232e-13],
          [3.2895e-15, 9.2467e-23]],

         [[9.8865e-14, 1.0000e+00],
          [1.9432e-09, 1.2591e-11]],

         [[1.0619e-06, 1.6585e-12],
          [7.7642e-16, 1.3544e-01]],

         [[1.0619e-06, 1.6585e-12],
          [7.7642e-16, 1.3544e-01]]],


        [[[5.9314e-01, 9.9765e-01],
          [9.3667e-01, 8.7855e-12]],

         [[1.0000e+00, 2.0792e-06],
          [9.9431e-01, 5.2087e-12]],

         [[2.8469e-14, 1.0000e+00],
          [1.0000e+00, 9.2998e-11]],

         [[1.0000e+00, 8.9864e-04],
          [1.2848e-05, 1.7079e-09]],

         [[1.0000e+00, 8.9864e-04],
          [1.2848e-05, 1.7079e-09]]]])


In [44]:
receptive_fields.shape
receptive_fields= receptive_fields.transpose(1, 3).add(torch.Tensor([0.1,1,1,1,2])).transpose(1,3)

In [45]:
print(receptive_fields)

tensor([[[[1.0942, 0.9190],
          [0.1000, 0.1000]],

         [[1.5233, 1.0000],
          [1.0000, 1.0000]],

         [[1.0000, 2.0000],
          [1.0000, 1.0000]],

         [[1.0000, 1.0000],
          [1.0000, 1.1354]],

         [[2.0000, 2.0000],
          [2.0000, 2.1354]]],


        [[[0.6931, 1.0977],
          [1.0367, 0.1000]],

         [[2.0000, 1.0000],
          [1.9943, 1.0000]],

         [[1.0000, 2.0000],
          [2.0000, 1.0000]],

         [[2.0000, 1.0009],
          [1.0000, 1.0000]],

         [[3.0000, 2.0009],
          [2.0000, 2.0000]]]])


In [46]:
print(receptive_fields.shape)

torch.Size([2, 5, 2, 2])


In [47]:
groups = torch.split(activations, 2, dim=1)
groups = list(groups)
print(groups)

[tensor([[[[  2.0685,   0.2549],
          [ -6.9292,  -8.5334]],

         [[ -0.4534, -15.2564],
          [-17.1740, -25.8676]]],


        [[[ -0.3115,   2.5259],
          [  0.8470, -13.2290]],

         [[  8.1133,  -7.0418],
          [  2.0821, -13.4903]]]]), tensor([[[[-15.4725,   6.7212],
          [-10.5295, -13.0490]],

         [[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[-16.0950,   6.6377],
          [ 17.8532, -12.0492]],

         [[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]]), tensor([[[[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]])]


### Test regularizer on activations in layer

#### calculate the numerator

In [48]:
print(groups[0].shape)
print(groups[0])

torch.Size([2, 2, 2, 2])
tensor([[[[  2.0685,   0.2549],
          [ -6.9292,  -8.5334]],

         [[ -0.4534, -15.2564],
          [-17.1740, -25.8676]]],


        [[[ -0.3115,   2.5259],
          [  0.8470, -13.2290]],

         [[  8.1133,  -7.0418],
          [  2.0821, -13.4903]]]])


In [49]:
difference_tensor = torch.sub(groups[0], groups[0][0][0])
difference_tensor_2 = torch.sub(groups[1], groups[1][0][0])
print(difference_tensor.shape)

torch.Size([2, 2, 2, 2])


In [50]:
print(difference_tensor.norm(1))
print(difference_tensor_2.norm(1))


tensor(90.0446)
tensor(126.8677)


In [51]:
difference_tensor

tensor([[[[  0.0000,   0.0000],
          [  0.0000,   0.0000]],

         [[ -2.5219, -15.5113],
          [-10.2448, -17.3342]]],


        [[[ -2.3800,   2.2710],
          [  7.7762,  -4.6956]],

         [[  6.0448,  -7.2967],
          [  9.0113,  -4.9569]]]])

In [52]:
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
batch_size = 2
for i in range(0, 2):
    current_group = groups[i]
    norm = torch.zeros(1)
    
    for j in range(0, 2):
        difference_tensor = torch.sub(current_group[j], current_group[j][0])
        print(difference_tensor)
        norm = norm  + difference_tensor.norm(1)
    
    #difference_tensor = torch.sub(current_group, current_group[0][0])
    l1_norms[i] = norm

tensor([[[  0.0000,   0.0000],
         [  0.0000,   0.0000]],

        [[ -2.5219, -15.5113],
         [-10.2448, -17.3342]]])
tensor([[[ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 8.4248, -9.5676],
         [ 1.2351, -0.2614]]])
tensor([[[  0.0000,   0.0000],
         [  0.0000,   0.0000]],

        [[  8.0948, -20.7838],
         [ -7.3665,  11.6222]]])
tensor([[[  0.0000,   0.0000],
         [  0.0000,   0.0000]],

        [[ 31.9531, -10.6446],
         [-23.9843,   1.4552]]])


In [53]:
l1_norms

tensor([ 65.1011, 115.9045])

In [54]:
current_group

tensor([[[[-15.4725,   6.7212],
          [-10.5295, -13.0490]],

         [[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[-16.0950,   6.6377],
          [ 17.8532, -12.0492]],

         [[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]])

In [55]:
current_group[0][0].shape

torch.Size([2, 2])

In [56]:
difference_tensor

tensor([[[  0.0000,   0.0000],
         [  0.0000,   0.0000]],

        [[ 31.9531, -10.6446],
         [-23.9843,   1.4552]]])

### calculate with denominator

In [57]:
print(groups[0].shape)
print(groups)

torch.Size([2, 2, 2, 2])
[tensor([[[[  2.0685,   0.2549],
          [ -6.9292,  -8.5334]],

         [[ -0.4534, -15.2564],
          [-17.1740, -25.8676]]],


        [[[ -0.3115,   2.5259],
          [  0.8470, -13.2290]],

         [[  8.1133,  -7.0418],
          [  2.0821, -13.4903]]]]), tensor([[[[-15.4725,   6.7212],
          [-10.5295, -13.0490]],

         [[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[-16.0950,   6.6377],
          [ 17.8532, -12.0492]],

         [[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]]), tensor([[[[ -7.3777, -14.0625],
          [-17.8959,  -1.4268]]],


        [[[ 15.8582,  -4.0069],
          [ -6.1312, -10.5940]]]])]


In [58]:
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = groups[i]
    # print(current_group.size())
    current_norm = torch.zeros(1)
    for j in range(0, 2):
        current_map_set = current_group[j]  
        print(current_map_set.shape)
        num = current_group.size(0)
        # print(num)
        sub_tensor = current_map_set.contiguous().view(num, -1)
        # print(sub_tensor.shape)
        sub_tensor_2 = current_map_set[0].view(-1,4)
        # print(sub_tensor_2.shape)
        difference_tensor = torch.sub(sub_tensor, sub_tensor_2)
        print(difference_tensor)
        num_tensor = difference_tensor.norm(1, dim=1)
        denom_tensor = torch.add(sub_tensor.norm(1, dim=1), sub_tensor_2.norm(1))
        value_tensor = torch.div(num_tensor, denom_tensor).norm(1)
        current_norm = current_norm + value_tensor
    l1_norms[i] = current_norm

torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ -2.5219, -15.5113, -10.2448, -17.3342]])
torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 8.4248, -9.5676,  1.2351, -0.2614]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [  8.0948, -20.7838,  -7.3665,  11.6222]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ 31.9531, -10.6446, -23.9843,   1.4552]])


In [329]:
import random
number_of_groups = 2
maps_per_group = int(len(activations[1]) / number_of_groups)
activation_groups = torch.split(activations, maps_per_group, dim=1)
activation_groups = list(activation_groups)
input = torch.empty(2)
groupwise_activation_norms = torch.zeros_like(input).cuda()
num_random_pairs = 2

for i in range(0, 2):
    current_group = activation_groups[i]
    batch_size = current_group.shape[0]
    num_of_filters = current_group.shape[1]
    random_map_indices = random.sample(range(0, num_of_filters), num_random_pairs)
    random_map_indices = torch.LongTensor(random_map_indices)
    selected_pairs = torch.index_select(current_group, 1, random_map_indices)
    selected_pair_groups = torch.split(selected_pairs, num_random_pairs//2, dim=1)
    selected_pair_groups = list(selected_pair_groups)
    difference_tensor = torch.sub(selected_pair_groups[0], selected_pair_groups[1])
    difference_tensor = difference_tensor.contiguous().view(-1,
                                                            difference_tensor.shape[2] *
                                                            difference_tensor.shape[3])
    print(difference_tensor)
    num_tensor_norm = difference_tensor.norm(1, dim=1)
    selected_pair_groups[0] = selected_pair_groups[0].view(-1,
                                                       selected_pair_groups[0].shape[2]*
                                                       selected_pair_groups[0].shape[3])
    selected_pair_groups[1] = selected_pair_groups[1].view(-1,
                                                       selected_pair_groups[1].shape[2]*
                                                       selected_pair_groups[1].shape[3])
    
    denom_tensor_norm = torch.add(selected_pair_groups[0].norm(1, dim=1),
                             selected_pair_groups[1].norm(1, dim=1))
    
    denom_tensor_norm = torch.add(denom_tensor_norm, num_tensor_norm)
    iou_map_wise = torch.div(2 * num_tensor_norm, denom_tensor_norm)
    iou_map_wise = torch.div(iou_map_wise, num_random_pairs)
    groupwise_activation_norms[i] = torch.div(iou_map_wise.norm(1), batch_size)
    
print(groupwise_activation_norms)


tensor([[ -2.1858,  15.0800,   2.3872,   5.5270],
        [ -9.8022, -21.1512,   4.7308,   0.5443]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([0.3390, 0.0000], device='cuda:0')


In [59]:
print(sub_tensor)

tensor([[-16.0950,   6.6377,  17.8532, -12.0492],
        [ 15.8582,  -4.0069,  -6.1312, -10.5940]])


In [60]:
print(denom_tensor)

tensor([105.2702,  89.2253])


In [61]:
print(num_tensor)

tensor([ 0.0000, 68.0373])


In [62]:
l1_norms

tensor([1.0050, 1.3157])

In [63]:
l1_norms

tensor([1.0050, 1.3157])

In [64]:
difference_tensor

tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ 31.9531, -10.6446, -23.9843,   1.4552]])

In [65]:
difference_tensor.norm(1, dim=1)

tensor([ 0.0000, 68.0373])

### Activation regularizer across a pair of layer

In [67]:
# our first set of activations are : <activations>
#create second set of activations
inputs = torch.randn(2,2,5,5)
activations_set2 = F.conv2d(inputs,mock_filter_combined)
activations_set2.shape

torch.Size([2, 5, 3, 3])

In [68]:
print(activations.shape)

torch.Size([2, 5, 2, 2])


In [69]:
maps_per_group = int(len(activations_set2[1]) / 2)
#print(maps_per_group)
activation_groups = torch.split(activations_set2, 2, dim=1)
activation_groups = list(activation_groups)

In [70]:
activation_groups

[tensor([[[[ -4.5527, -18.1321,  16.7374],
           [-28.2286, -23.0370,  -6.3070],
           [-24.6740, -32.5130, -16.3835]],
 
          [[-19.3668, -18.4149,  25.9876],
           [-19.5884, -31.2367,  -0.7901],
           [-19.3203, -58.2871,   0.1974]]],
 
 
         [[[ -0.3672, -20.0485, -32.0842],
           [ 19.9001,  -1.1771, -26.2464],
           [ 15.1241,   2.3370,  -9.4676]],
 
          [[ 11.1805,   6.6425, -32.4661],
           [ 32.9930,  -5.7652, -47.9725],
           [ 22.8655, -16.8197, -35.0720]]]]),
 tensor([[[[-12.7268,  -1.2030,   2.4297],
           [ -5.9311, -26.6071, -16.3488],
           [-33.3784,   3.0060, -41.1298]],
 
          [[-14.2059,  -4.0345,  -8.9748],
           [  6.9010, -30.6611,  11.7742],
           [-20.9535, -16.3840,  -4.6613]]],
 
 
         [[[ -4.1640,   0.6039,  -7.7638],
           [ 12.7781,  13.2537, -11.0101],
           [ -0.2555,  11.8302,  -3.2664]],
 
          [[ 14.4106,   8.2022, -20.8819],
           [ 21.5114,  -9.

In [71]:
maps_per_group = int(len(activations[1]) / 2)
#print(maps_per_group)
activation_groups_layer_1 = torch.split(activations, 2, dim=1)
activation_groups_layer_1 = list(activation_groups_layer_1)

In [72]:
activation_groups_layer_1

[tensor([[[[ -1.4883,   1.5331],
           [  1.3515, -14.5159]],
 
          [[  3.7410,   9.9899],
           [ -2.9278,  -4.1096]]],
 
 
         [[[-20.0256, -27.7341],
           [  4.4577,  -2.9896]],
 
          [[-19.3353,  -2.7643],
           [ -0.1280,  -1.9527]]]]), tensor([[[[-28.9301,   4.9425],
           [ -3.6189,   0.0523]],
 
          [[-13.0393,  27.1812],
           [ 18.0646,  -0.0906]]],
 
 
         [[[ -7.0356, -22.2357],
           [  1.2545,  -6.3595]],
 
          [[-10.5295,   0.4721],
           [ -0.5041,  -0.1237]]]]), tensor([[[[-13.0393,  27.1812],
           [ 18.0646,  -0.0906]]],
 
 
         [[[-10.5295,   0.4721],
           [ -0.5041,  -0.1237]]]])]

In [73]:
input = torch.empty(2)
groupwise_activation_norms = torch.zeros_like(input)

In [74]:
for i in range(0, 2):
    current_group = activation_groups[i]
    current_group_layer_1 = activation_groups_layer_1[i]
    
    num = current_group.size(0) * current_group.size(1)
    size_of_map = current_group.size(2) * current_group.size(3)
    size_of_map_layer_1 = current_group_layer_1.size(2) * current_group_layer_1.size(3)
    
    map_per_row_view = current_group.contiguous().view(num, -1)       # shape: (Batches*Channels) X (Height * Width)
    first_map_row_view =  current_group_layer_1[0][0].view(-1, size_of_map_layer_1)  # shape: 1 X (Height * Width)
    
    difference_tensor = torch.sub(map_per_row_view, first_map_row_view)
    numerator_tensor = difference_tensor.norm(1, dim=1)
    denominator_tensor = torch.add(map_per_row_view.norm(1, dim=1), first_map_row_view.norm(1))
    groupwise_activation_norms[i] = torch.div(numerator_tensor, denominator_tensor).sum()

RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1

In [75]:
activation_groups[i].shape

torch.Size([2, 2, 3, 3])

In [76]:
activation_groups_layer_1[i].shape

torch.Size([2, 2, 2, 2])

In [77]:
activation_groups_layer_1[i][0][0].unsqueeze(0)

tensor([[[ -1.4883,   1.5331],
         [  1.3515, -14.5159]]])

### Applying the activation norm across the whole batch now

In [242]:
inputs = torch.randn(3,2,5,5)
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([3, 5, 3, 3])

In [243]:
mock_filter_combined.shape

torch.Size([5, 2, 3, 3])

In [244]:
maps_per_group = int(len(activations[1]) / 2)
print(maps_per_group)
activation_groups = torch.split(activations, 2, dim=1)
activation_groups = list(activation_groups)

2


In [245]:
print(len(activation_groups))
for i in range(len(activation_groups)):
    print(activation_groups[i].shape)

3
torch.Size([3, 2, 3, 3])
torch.Size([3, 2, 3, 3])
torch.Size([3, 1, 3, 3])


In [246]:
# Testing for each image a neuron is chosen
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = groups[i]
    # print(current_group.size())
    current_norm = torch.zeros(1)
    for j in range(0, 2):
        current_map_set = current_group[j]  
        print(current_map_set.shape)
        num = current_group.size(0)
        # print(num)
        sub_tensor = current_map_set.contiguous().view(num, -1)
        # print(sub_tensor.shape)
        sub_tensor_2 = current_map_set[0].view(-1,4)
        # print(sub_tensor_2.shape)
        difference_tensor = torch.sub(sub_tensor, sub_tensor_2)
        print(difference_tensor)
        num_tensor = difference_tensor.norm(1, dim=1)
        denom_tensor = torch.add(sub_tensor.norm(1, dim=1), sub_tensor_2.norm(1))
        value_tensor = torch.div(num_tensor, denom_tensor).norm(1)
        current_norm = current_norm + value_tensor
    l1_norms[i] = current_norm
print(l1_norms)

torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ -2.5219, -15.5113, -10.2448, -17.3342]])
torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 8.4248, -9.5676,  1.2351, -0.2614]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [  8.0948, -20.7838,  -7.3665,  11.6222]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ 31.9531, -10.6446, -23.9843,   1.4552]])
tensor([1.0050, 1.3157])


In [319]:
## Testing for each batch a neuron is chosen
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = activation_groups[i]
    batch_size = current_group.shape[0]
    first_filter_maps = current_group[:,0, :].unsqueeze(1)
    difference_tensor = torch.sub(current_group, first_filter_maps)
    difference_tensor = difference_tensor.contiguous().view(-1, 
                                                    difference_tensor.shape[2] * difference_tensor.shape[3])
    num_tensor_norm = difference_tensor.norm(1, dim=1)
    first_filter_map_view = first_filter_maps.view(first_filter_maps.shape[0], first_filter_maps.shape[1], 
                                                    first_filter_maps.shape[2] * first_filter_maps.shape[3])
    first_filter_map_norms = first_filter_map_view.norm(1, dim=2)
    current_group_view = current_group.view(current_group.shape[0], current_group.shape[1],
                                           current_group.shape[2] * current_group.shape[3])
    current_group_norms = current_group_view.norm(1, dim=2)
    denom_tensor_part = torch.add(first_filter_map_norms, current_group_norms)
    denom_tensor_part_view = denom_tensor_part.view(-1)
    denom_tensor_norm = torch.add(denom_tensor_part_view, 
                            num_tensor_norm)
    iou_map_wise = torch.div(num_tensor_norm, denom_tensor_norm)
    l1_norms[i] = torch.div(iou_map_wise.norm(1), batch_size)

print('groupwise norm', l1_norms)

groupwise norm tensor([0.7488, 0.3784])


torch.Size([2, 2, 2, 3, 3])
tensor([[[[[  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000]],

          [[  4.0266,  -7.2197,   5.2777],
           [ 12.2109,  -8.6519,   0.5928],
           [ 19.4633, -16.0423, -11.7876]]],


         [[[  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000]],

          [[-10.1628, -22.6971,   1.1106],
           [  5.3785,  -9.5315,  -1.2909],
           [ 13.8482,  15.5995,   0.0899]]]],



        [[[[  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000]],

          [[  0.6715, -26.1176,   8.6479],
           [ -2.5443, -36.7349,   1.8670],
           [  5.4857, -22.1145,  -5.0489]]],


         [[[  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000],
           [  0.0000,   0.0000,   0.0000]],

          [[ -8.3782, -29.2438,  -1.2212],
    

In [193]:
current_group

tensor([[[[[ 25.5460,   4.7404, -19.1055],
           [ 25.9596,  14.5644,  18.3110],
           [ 26.6828,  58.3140,  49.8822]],

          [[ 29.5726,  -2.4793, -13.8277],
           [ 38.1705,   5.9125,  18.9038],
           [ 46.1461,  42.2717,  38.0946]]],


         [[[ 22.7896,  16.6343,   9.2752],
           [ 12.4162,   5.2449,  16.0265],
           [ 15.6306,  17.5061,  37.3006]],

          [[ 12.6268,  -6.0628,  10.3858],
           [ 17.7947,  -4.2866,  14.7356],
           [ 29.4789,  33.1056,  37.3904]]]],



        [[[[ 28.1389,  26.6243,  -7.9718],
           [ 22.9789,  27.5569,  -3.9408],
           [ 17.2564,  36.7730,  46.4289]],

          [[ 28.8103,   0.5068,   0.6761],
           [ 20.4346,  -9.1780,  -2.0738],
           [ 22.7421,  14.6585,  41.3800]]],


         [[[ 13.2591,  23.6378,   8.0095],
           [ -7.7992,  16.0346,   8.8269],
           [ 21.3490,  -4.3305,  31.6540]],

          [[  4.8809,  -5.6060,   6.7883],
           [  3.8682,   2.9915, 

In [87]:
# a = torch.Tensor(2,2,3,3)
# print('a:', a)
# b = a[:,0,:,:].unsqueeze(1)
# print('shape of b:', b.shape)
# print('b:', b)
# c = torch.sub(b, a)

# print('c shape:', c.shape)
# print('c:', c[:,0,:,:])

In [136]:
a = torch.Tensor([2,3,4])
c = a.norm(1)

In [179]:
activation_groups[2].shape

torch.Size([2, 1, 3, 3])

In [182]:
current_group = torch.stack(activation_groups[:2], dim=0)
current_group.shape
first_filter_maps = current_group[:,:, 0, :, :].unsqueeze(2)
first_filter_maps.shape

torch.Size([2, 2, 1, 3, 3])

### Comparing two neurons from different group and same groups:

In [79]:
def purely_diff_based_measure(unit_x, unit_y, feature_maps):
    
    
    

NameError: name 'purely_diff_based_measure' is not defined

In [80]:
mock_filter_combined.shape

torch.Size([5, 2, 3, 3])

In [84]:
inputs = torch.randn(2,2,4,4)

In [85]:
inputs

tensor([[[[ 0.7321, -0.2079,  1.5025, -1.2202],
          [-1.6360,  0.2292, -0.3381, -0.0331],
          [-0.1250,  1.0014, -0.8525, -0.9578],
          [ 1.3452,  1.5831,  0.1439,  0.5800]],

         [[ 0.3350,  1.7472,  0.0860, -1.7742],
          [-0.9988,  0.2592,  1.5437, -1.2707],
          [ 0.8323,  0.9461,  0.7537, -0.0528],
          [ 0.5220, -0.6177,  0.5546,  0.3272]]],


        [[[-1.5640, -0.6262,  0.4593,  0.3129],
          [-0.0613,  0.5867,  1.3038,  0.4860],
          [-0.6078,  0.0202, -0.0098,  0.4428],
          [-1.0598,  0.9279,  1.4967,  0.0815]],

         [[-0.8611,  0.4072, -0.1977,  0.1255],
          [ 0.2636, -1.1961,  2.0308, -0.4275],
          [-1.0225,  1.0798, -1.1144, -1.6496],
          [-0.4293,  2.8448, -0.2664,  0.3503]]]])

In [86]:
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([2, 5, 2, 2])

In [87]:
activations

tensor([[[[25.5321,  3.9110],
          [31.8075, 17.9826]],

         [[44.8827, -6.0560],
          [46.2906, 10.6101]],

         [[14.8567, 17.0462],
          [28.0564, 24.9592]],

         [[34.9558, -4.6231],
          [13.8158, -0.9317]],

         [[34.9558, -4.6231],
          [13.8158, -0.9317]]],


        [[[ 0.9630,  2.2310],
          [25.1521, 32.4894]],

         [[ 1.6677, 20.9894],
          [52.8303, 31.9127]],

         [[ 8.2962, -0.9387],
          [-2.3180, 53.6844]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]]]])

In [109]:
std_map_wise

tensor([[[[25.5321,  3.9110],
          [31.8075, 17.9826]],

         [[ 0.9630,  2.2310],
          [25.1521, 32.4894]]],


        [[[44.8827, -6.0560],
          [46.2906, 10.6101]],

         [[ 1.6677, 20.9894],
          [52.8303, 31.9127]]],


        [[[14.8567, 17.0462],
          [28.0564, 24.9592]],

         [[ 8.2962, -0.9387],
          [-2.3180, 53.6844]]],


        [[[34.9558, -4.6231],
          [13.8158, -0.9317]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]]],


        [[[34.9558, -4.6231],
          [13.8158, -0.9317]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]]]])

In [93]:
activations[:,4]

tensor([[[34.9558, -4.6231],
         [13.8158, -0.9317]],

        [[13.6379,  8.4810],
         [36.4244,  6.9291]]])

In [95]:
unit_x = 0
unit_y = 1
act_unit_x = activations[:, unit_x]
act_unit_y = activations[:, unit_y]

In [96]:
act_unit_x

tensor([[[25.5321,  3.9110],
         [31.8075, 17.9826]],

        [[ 0.9630,  2.2310],
         [25.1521, 32.4894]]])

In [97]:
act_unit_y

tensor([[[44.8827, -6.0560],
         [46.2906, 10.6101]],

        [[ 1.6677, 20.9894],
         [52.8303, 31.9127]]])

In [98]:
act_unit_y.shape

torch.Size([2, 2, 2])

In [100]:
number_of_maps = activations.size(1)

In [102]:
number_of_maps

5

In [110]:
std_map_wise = activations.transpose(0, 1).contiguous().view(number_of_maps, -1).std(1)

In [111]:
std_map_wise.shape

torch.Size([5])

In [114]:
activations

tensor([[[[25.5321,  3.9110],
          [31.8075, 17.9826]],

         [[44.8827, -6.0560],
          [46.2906, 10.6101]],

         [[14.8567, 17.0462],
          [28.0564, 24.9592]],

         [[34.9558, -4.6231],
          [13.8158, -0.9317]],

         [[34.9558, -4.6231],
          [13.8158, -0.9317]]],


        [[[ 0.9630,  2.2310],
          [25.1521, 32.4894]],

         [[ 1.6677, 20.9894],
          [52.8303, 31.9127]],

         [[ 8.2962, -0.9387],
          [-2.3180, 53.6844]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]],

         [[13.6379,  8.4810],
          [36.4244,  6.9291]]]])

In [120]:
receptive_fields = activations.transpose(1, 3).div(std_map_wise).transpose(1, 3)

In [122]:
receptive_fields.shape

torch.Size([2, 5, 2, 2])

In [123]:
receptive_fields

tensor([[[[ 1.9153,  0.2934],
          [ 2.3860,  1.3490]],

         [[ 2.0360, -0.2747],
          [ 2.0999,  0.4813]],

         [[ 0.8197,  0.9405],
          [ 1.5480,  1.3771]],

         [[ 2.3186, -0.3067],
          [ 0.9164, -0.0618]],

         [[ 2.3186, -0.3067],
          [ 0.9164, -0.0618]]],


        [[[ 0.0722,  0.1674],
          [ 1.8868,  2.4372]],

         [[ 0.0757,  0.9521],
          [ 2.3965,  1.4476]],

         [[ 0.4577, -0.0518],
          [-0.1279,  2.9621]],

         [[ 0.9046,  0.5625],
          [ 2.4160,  0.4596]],

         [[ 0.9046,  0.5625],
          [ 2.4160,  0.4596]]]])

In [124]:
receptive_fields = torch.sigmoid(receptive_fields)

In [284]:
receptive_fields

tensor([[[[0.8716, 0.5728],
          [0.9158, 0.7940]],

         [[0.8845, 0.4317],
          [0.8909, 0.6181]],

         [[0.6942, 0.7192],
          [0.8246, 0.7985]],

         [[0.9104, 0.4239],
          [0.7143, 0.4846]],

         [[0.9104, 0.4239],
          [0.7143, 0.4846]]],


        [[[0.5181, 0.5417],
          [0.8684, 0.9196]],

         [[0.5189, 0.7215],
          [0.9166, 0.8096]],

         [[0.6125, 0.4871],
          [0.4681, 0.9508]],

         [[0.7119, 0.6370],
          [0.9180, 0.6129]],

         [[0.7119, 0.6370],
          [0.9180, 0.6129]]]])

In [285]:
unit_x = 0
unit_y = 1
act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]

In [286]:
act_unit_y.shape

torch.Size([2, 2, 2])

In [287]:
act_unit_x

tensor([[[0.8716, 0.5728],
         [0.9158, 0.7940]],

        [[0.5181, 0.5417],
         [0.8684, 0.9196]]])

In [288]:
act_unit_y

tensor([[[0.8845, 0.4317],
         [0.8909, 0.6181]],

        [[0.5189, 0.7215],
         [0.9166, 0.8096]]])

In [213]:
difference_tensor = act_unit_x - act_unit_y

In [289]:
hadamard_prod = torch.mul(act_unit_x, act_unit_y)

In [290]:
hadamard_prod

tensor([[[0.7710, 0.2473],
         [0.8158, 0.4907]],

        [[0.2688, 0.3909],
         [0.7959, 0.7446]]])

In [214]:
difference_tensor

tensor([[[-0.0129,  0.1411],
         [ 0.0249,  0.1759]],

        [[-0.0009, -0.1798],
         [-0.0482,  0.1100]]])

In [215]:
difference_tensor.norm(1)

tensor(0.6936)

In [291]:
hadamard_prod.norm(1)

tensor(4.5250)

In [216]:
score = (2 * difference_tensor.norm(1)) / (act_unit_x.norm(1) + act_unit_y.norm(1) + difference_tensor.norm(1))

In [217]:
score

tensor(0.1111)

In [296]:
unit_x = 2
unit_y = 3
act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]
difference_tensor = act_unit_x - act_unit_y
hadamard_prod = torch.mul(act_unit_x, act_unit_y)
print(difference_tensor)

tensor([[[-0.2162,  0.2953],
         [ 0.1103,  0.3140]],

        [[-0.0994, -0.1500],
         [-0.4500,  0.3379]]])


In [297]:
difference_tensor.norm(1)

tensor(1.9731)

In [305]:
hadamard_prod

tensor([[[0.6320, 0.3049],
         [0.5890, 0.3869]],

        [[0.4360, 0.3103],
         [0.4297, 0.5828]]])

In [220]:
score = (2 * difference_tensor.norm(1)) / (act_unit_x.norm(1) + act_unit_y.norm(1) + difference_tensor.norm(1))

In [221]:
score

tensor(0.3049)

In [197]:
receptive_fields.shape

torch.Size([2, 5, 2, 2])

In [306]:
unit_x = np.array([0 ,2])
unit_y = np.array([1 ,3])

act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]

In [307]:
act_unit_x[:,0]

tensor([[[0.8716, 0.5728],
         [0.9158, 0.7940]],

        [[0.5181, 0.5417],
         [0.8684, 0.9196]]])

In [308]:
act_unit_y[:,0]

tensor([[[0.8845, 0.4317],
         [0.8909, 0.6181]],

        [[0.5189, 0.7215],
         [0.9166, 0.8096]]])

In [309]:
difference_tensor = act_unit_x - act_unit_y

In [310]:
difference_tensor[:, 0]

tensor([[[-0.0129,  0.1411],
         [ 0.0249,  0.1759]],

        [[-0.0009, -0.1798],
         [-0.0482,  0.1100]]])

In [311]:
difference_tensor[:, 1]

tensor([[[-0.2162,  0.2953],
         [ 0.1103,  0.3140]],

        [[-0.0994, -0.1500],
         [-0.4500,  0.3379]]])

In [312]:
hadamard_tensor = torch.mul(act_unit_x, act_unit_y)

In [314]:
hadamard_tensor[:,0]

tensor([[[0.7710, 0.2473],
         [0.8158, 0.4907]],

        [[0.2688, 0.3909],
         [0.7959, 0.7446]]])

In [280]:
score = []
for i in range(len(unit_x)):
    score.append((2 * difference_tensor[:,i].norm(1)) 
                 / (act_unit_x[:, i].norm(1) + act_unit_y[:, i].norm(1) + difference_tensor[:,i].norm(1)))

In [281]:
difference_tensor.shape

torch.Size([2, 2, 2, 2])

In [282]:
torch.stack(score)

tensor([0.1111, 0.3049])

In [283]:
score

[tensor(0.1111), tensor(0.3049)]