In [2]:
import numpy as np

In [3]:
import torch

In [4]:
x = torch.FloatTensor([[1,2,3,4,5,6,7],[3,5,6,7,8,4,5]])
x

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [3., 5., 6., 7., 8., 4., 5.]])

In [5]:
x.unfold(0,2,2)

tensor([[[1., 3.],
         [2., 5.],
         [3., 6.],
         [4., 7.],
         [5., 8.],
         [6., 4.],
         [7., 5.]]])

In [6]:
mock_filter_1 = torch.tensor([[1.0,2,1],[2,4,5],[6,7,8]])
mock_filter_2 = torch.tensor([[1.0,6,7],[1,9,5],[4,7,8]])
mock_filter_3 = torch.tensor([[1.0,3,1],[7,0,5],[9,7,0]])
mock_filter_4 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])

In [7]:
mock_filter_combined = torch.stack([mock_filter_1, mock_filter_2, mock_filter_3, mock_filter_4]) 

In [8]:
mock_filter_combined = torch.stack([mock_filter_combined, mock_filter_combined], dim=1)

In [9]:
mock_filter_combined.shape

torch.Size([4, 2, 3, 3])

In [10]:
print(mock_filter_combined[0])
print(mock_filter_combined[1])
print(mock_filter_combined[2])
print(mock_filter_combined[3])

tensor([[[1., 2., 1.],
         [2., 4., 5.],
         [6., 7., 8.]],

        [[1., 2., 1.],
         [2., 4., 5.],
         [6., 7., 8.]]])
tensor([[[1., 6., 7.],
         [1., 9., 5.],
         [4., 7., 8.]],

        [[1., 6., 7.],
         [1., 9., 5.],
         [4., 7., 8.]]])
tensor([[[1., 3., 1.],
         [7., 0., 5.],
         [9., 7., 0.]],

        [[1., 3., 1.],
         [7., 0., 5.],
         [9., 7., 0.]]])
tensor([[[3., 2., 4.],
         [0., 4., 5.],
         [1., 7., 0.]],

        [[3., 2., 4.],
         [0., 4., 5.],
         [1., 7., 0.]]])


In [11]:
filter_groups = mock_filter_combined.unfold(0, 2, 2)

In [12]:
filter_groups.shape

torch.Size([2, 2, 3, 3, 2])

In [13]:
filter_groups[0].permute(3,0,1,2)

tensor([[[[1., 2., 1.],
          [2., 4., 5.],
          [6., 7., 8.]],

         [[1., 2., 1.],
          [2., 4., 5.],
          [6., 7., 8.]]],


        [[[1., 6., 7.],
          [1., 9., 5.],
          [4., 7., 8.]],

         [[1., 6., 7.],
          [1., 9., 5.],
          [4., 7., 8.]]]])

In [14]:
filter_groups[1].permute(3,0,1,2)

tensor([[[[1., 3., 1.],
          [7., 0., 5.],
          [9., 7., 0.]],

         [[1., 3., 1.],
          [7., 0., 5.],
          [9., 7., 0.]]],


        [[[3., 2., 4.],
          [0., 4., 5.],
          [1., 7., 0.]],

         [[3., 2., 4.],
          [0., 4., 5.],
          [1., 7., 0.]]]])

### Testing the activations

In [15]:
import torch.nn.functional as F

In [16]:
filters = mock_filter_combined
filters.shape

torch.Size([4, 2, 3, 3])

In [17]:
inputs = torch.randn(2,2,4,4)

In [18]:
activations = F.conv2d(inputs,filters)

In [19]:
activations.shape

torch.Size([2, 4, 2, 2])

In [20]:
inputs

tensor([[[[-9.9850e-02,  4.6968e-01,  2.6587e-01,  1.5696e+00],
          [-5.0539e-01, -7.3806e-02,  1.2739e-02,  1.0668e+00],
          [-3.6673e-01,  4.1080e-01, -7.1179e-02,  5.8535e-02],
          [-4.4407e-01, -1.4111e+00, -2.8855e-01,  3.2753e-01]],

         [[-9.2353e-01,  3.5978e-01, -6.4503e-01, -4.1743e-01],
          [ 9.7220e-01,  1.6586e+00,  3.8452e-01,  2.3972e-01],
          [ 1.0739e+00, -7.3287e-01, -2.6750e-01,  5.0841e-01],
          [ 8.9542e-01, -1.0102e+00, -1.1399e+00,  1.9715e-01]]],


        [[[ 1.5995e+00,  6.3038e-01,  2.7255e+00, -4.4879e-01],
          [-1.3059e-01,  2.4321e+00,  3.9858e-01, -1.8686e-01],
          [-1.3590e+00,  1.2190e+00, -1.4175e-01, -7.9056e-01],
          [ 1.8291e+00, -2.0615e-01,  1.1696e+00, -2.2797e+00]],

         [[-2.0379e+00,  1.9073e+00, -1.0902e+00, -1.6716e+00],
          [-9.0178e-01,  1.6256e+00,  5.7807e-01, -2.1041e-01],
          [-8.7855e-01,  1.8043e-03,  4.5222e-01, -1.1819e-01],
          [-4.2819e-01, -6.4969e

In [21]:
activations

tensor([[[[  8.7945,  12.7468],
          [-23.2027, -15.8082]],

         [[ 15.8802,  19.1888],
          [-17.7002,  -2.9088]],

         [[ 10.4498,  13.2008],
          [ -4.0120, -27.1280]],

         [[  3.8503,  11.7674],
          [-13.3205,  -0.1658]]],


        [[[ 22.9261,  15.9519],
          [ 37.3751,  -0.3215]],

         [[ 68.6843,   8.1547],
          [ 65.0060,   3.2447]],

         [[ -5.1254,  44.9018],
          [  4.6241,  24.7128]],

         [[ 37.7237,   7.7164],
          [ 10.7707,  30.2024]]]])

In [22]:
groups = torch.split(activations, 2, dim=1)

In [23]:
groups

(tensor([[[[  8.7945,  12.7468],
           [-23.2027, -15.8082]],
 
          [[ 15.8802,  19.1888],
           [-17.7002,  -2.9088]]],
 
 
         [[[ 22.9261,  15.9519],
           [ 37.3751,  -0.3215]],
 
          [[ 68.6843,   8.1547],
           [ 65.0060,   3.2447]]]]), tensor([[[[ 10.4498,  13.2008],
           [ -4.0120, -27.1280]],
 
          [[  3.8503,  11.7674],
           [-13.3205,  -0.1658]]],
 
 
         [[[ -5.1254,  44.9018],
           [  4.6241,  24.7128]],
 
          [[ 37.7237,   7.7164],
           [ 10.7707,  30.2024]]]]))

In [24]:
groups[0]

tensor([[[[  8.7945,  12.7468],
          [-23.2027, -15.8082]],

         [[ 15.8802,  19.1888],
          [-17.7002,  -2.9088]]],


        [[[ 22.9261,  15.9519],
          [ 37.3751,  -0.3215]],

         [[ 68.6843,   8.1547],
          [ 65.0060,   3.2447]]]])

### Another test case where filtere are not divisible by the number of groups

In [25]:
mock_filter_1 = torch.tensor([[1.0,2,1],[2,4,5],[6,7,8]])
mock_filter_2 = torch.tensor([[1.0,6,7],[1,9,5],[4,7,8]])
mock_filter_3 = torch.tensor([[1.0,3,1],[7,0,5],[9,7,0]])
mock_filter_4 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])
mock_filter_5 = torch.tensor([[3.0,2,4],[0,4,5],[1,7,0]])
mock_filter_6 = torch.tensor([[3.0,2,5],[1,8,0],[2,5,8]])
mock_filter_7 = torch.tensor([[4.0,6,9],[0,0,5],[1,3,7]])

In [26]:
mock_filter_combined = torch.stack([mock_filter_1, mock_filter_2, mock_filter_3, mock_filter_4,mock_filter_5,
                                   mock_filter_6, mock_filter_7]) 

In [27]:
mock_filter_combined = torch.stack([mock_filter_combined, mock_filter_combined], dim=1)
mock_filter_combined.shape

torch.Size([7, 2, 3, 3])

In [28]:
inputs = torch.randn(2,2,4,4)

In [29]:
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([2, 7, 2, 2])

In [30]:
inputs

tensor([[[[ 3.8571e-01,  1.5037e+00,  8.7711e-01, -9.7449e-01],
          [-5.8401e-01, -5.8842e-01, -1.0952e+00, -1.6888e+00],
          [-2.2338e-01,  1.9856e-01,  1.7527e+00,  6.1884e-01],
          [ 1.1804e+00, -1.1167e+00,  5.7511e-01,  2.2623e+00]],

         [[ 2.2318e+00,  2.4331e-01,  3.6069e-01,  1.6768e+00],
          [ 5.6614e-01,  1.5589e+00,  5.7866e-01,  7.4887e-01],
          [-2.3629e-01,  1.6206e-01,  1.0245e+00,  5.0072e-01],
          [ 6.9069e-01, -6.2059e-01,  6.0690e-01, -3.9473e-01]]],


        [[[ 1.1432e+00, -4.1473e-01,  5.8279e-01, -1.5270e-01],
          [ 1.6269e-03,  1.5814e-01,  8.7467e-01, -1.1829e+00],
          [ 1.3435e-01,  1.4104e+00,  1.0563e+00, -6.8253e-02],
          [-2.0916e-01,  1.9054e+00,  8.8494e-01, -1.1731e+00]],

         [[ 9.4696e-01, -2.9829e-01,  1.5971e+00,  5.7616e-01],
          [ 4.8528e-01, -1.4352e+00,  1.2214e+00,  1.4739e+00],
          [-6.7575e-01,  2.0031e+00, -4.7757e-01, -1.1840e-03],
          [ 1.6427e-01,  1.6352e

In [31]:
activations

tensor([[[[30.5966, 30.6605],
          [24.3373, 29.2164]],

         [[50.8009, 35.5511],
          [23.6404, 38.5105]],

         [[ 4.7757, 30.9422],
          [17.7242, -0.7584]],

         [[19.6616, 23.5610],
          [ 4.8597, 21.3619]],

         [[19.6616, 23.5610],
          [ 4.8597, 21.3619]],

         [[48.3828, 31.6299],
          [ 6.2416, 37.1330]],

         [[49.5723, 32.5651],
          [19.9215, 12.8028]]],


        [[[34.4659, 35.3320],
          [49.9759, 29.8387]],

         [[38.9041, 51.5231],
          [75.1428, 32.3679]],

         [[35.0414, 33.5382],
          [22.2364, 69.4363]],

         [[42.2892, 21.2186],
          [48.5784, 15.7545]],

         [[42.2892, 21.2186],
          [48.5784, 15.7545]],

         [[26.6290, 28.9950],
          [63.7339, 11.0429]],

         [[47.9325, 20.1572],
          [35.3421,  6.4070]]]])

In [32]:
groups = torch.split(activations, 2, dim=1)
list(groups)

[tensor([[[[30.5966, 30.6605],
           [24.3373, 29.2164]],
 
          [[50.8009, 35.5511],
           [23.6404, 38.5105]]],
 
 
         [[[34.4659, 35.3320],
           [49.9759, 29.8387]],
 
          [[38.9041, 51.5231],
           [75.1428, 32.3679]]]]), tensor([[[[ 4.7757, 30.9422],
           [17.7242, -0.7584]],
 
          [[19.6616, 23.5610],
           [ 4.8597, 21.3619]]],
 
 
         [[[35.0414, 33.5382],
           [22.2364, 69.4363]],
 
          [[42.2892, 21.2186],
           [48.5784, 15.7545]]]]), tensor([[[[19.6616, 23.5610],
           [ 4.8597, 21.3619]],
 
          [[48.3828, 31.6299],
           [ 6.2416, 37.1330]]],
 
 
         [[[42.2892, 21.2186],
           [48.5784, 15.7545]],
 
          [[26.6290, 28.9950],
           [63.7339, 11.0429]]]]), tensor([[[[49.5723, 32.5651],
           [19.9215, 12.8028]]],
 
 
         [[[47.9325, 20.1572],
           [35.3421,  6.4070]]]])]

In [33]:
groupwise_mean = [torch.mean(groups[i]) for i in range(0,2)]

In [34]:
groupwise_mean

[tensor(38.1790), tensor(25.6388)]

In [35]:
groupwise_std = [torch.std(groups[i]) for i in range(0,2)]
groupwise_std

[tensor(13.0969), tensor(17.7281)]

### Test channelwise receptive field calcualtions

In [36]:
def calculate_receptive_field_layer_no_batch_norm(feature_maps, linear_map_param_1, 
                                                  linear_map_param_2):
    number_of_maps = feature_maps[1]
    std_map_wise = feature_maps.transpose(0,1).contiguous().view(number_of_maps, -1).std(1)
    receptive_fields = feature_maps.transpose(1,3).div(std_map_wise).transpose(1,3)
    receptive_fields = torch.sigmoid(linear_map_param_1 * receptive_fields + linear_map_param_2)
    return receptive_fields

In [37]:
calculate_receptive_field_layer_no_batch_norm(activations)
print(activations.shape)

TypeError: calculate_receptive_field_layer_no_batch_norm() missing 2 required positional arguments: 'linear_map_param_1' and 'linear_map_param_2'

In [ ]:
kk=activations.transpose(0,1)
print(kk.shape)
c =kk.contiguous().view(5, -1)

In [ ]:
c.shape

In [ ]:
B = torch.mean(c,1)
c.std(1)

In [ ]:
print(activations)
print(activations.shape)

In [ ]:
kk=activations.transpose(1,3)
print(kk)
print(kk.shape)
activations.transpose(1,3).div(torch.Tensor([0.1,1,1,1,1])).transpose(1,3)

In [ ]:
receptive_fields = 2.0 * activations + 1.0
print(receptive_fields)

In [ ]:
receptive_fields = torch.sigmoid(receptive_fields)
print(receptive_fields)

In [ ]:
receptive_fields.shape
receptive_fields= receptive_fields.transpose(1, 3).add(torch.Tensor([0.1,1,1,1,2])).transpose(1,3)

In [ ]:
print(receptive_fields)

In [ ]:
print(receptive_fields.shape)

In [ ]:
groups = torch.split(activations, 2, dim=1)
groups = list(groups)
print(groups)

### Test regularizer on activations in layer

#### calculate the numerator

In [ ]:
print(groups[0].shape)
print(groups[0])

In [ ]:
difference_tensor = torch.sub(groups[0], groups[0][0][0])
difference_tensor_2 = torch.sub(groups[1], groups[1][0][0])
print(difference_tensor.shape)

In [ ]:
print(difference_tensor.norm(1))
print(difference_tensor_2.norm(1))


In [ ]:
difference_tensor

In [ ]:
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
batch_size = 2
for i in range(0, 2):
    current_group = groups[i]
    norm = torch.zeros(1)
    
    for j in range(0, 2):
        difference_tensor = torch.sub(current_group[j], current_group[j][0])
        print(difference_tensor)
        norm = norm  + difference_tensor.norm(1)
    
    #difference_tensor = torch.sub(current_group, current_group[0][0])
    l1_norms[i] = norm

In [ ]:
l1_norms

In [ ]:
current_group

In [ ]:
current_group[0][0].shape

In [ ]:
difference_tensor

### calculate with denominator

In [38]:
print(groups[0].shape)
print(groups)

torch.Size([2, 2, 2, 2])
(tensor([[[[30.5966, 30.6605],
          [24.3373, 29.2164]],

         [[50.8009, 35.5511],
          [23.6404, 38.5105]]],


        [[[34.4659, 35.3320],
          [49.9759, 29.8387]],

         [[38.9041, 51.5231],
          [75.1428, 32.3679]]]]), tensor([[[[ 4.7757, 30.9422],
          [17.7242, -0.7584]],

         [[19.6616, 23.5610],
          [ 4.8597, 21.3619]]],


        [[[35.0414, 33.5382],
          [22.2364, 69.4363]],

         [[42.2892, 21.2186],
          [48.5784, 15.7545]]]]), tensor([[[[19.6616, 23.5610],
          [ 4.8597, 21.3619]],

         [[48.3828, 31.6299],
          [ 6.2416, 37.1330]]],


        [[[42.2892, 21.2186],
          [48.5784, 15.7545]],

         [[26.6290, 28.9950],
          [63.7339, 11.0429]]]]), tensor([[[[49.5723, 32.5651],
          [19.9215, 12.8028]]],


        [[[47.9325, 20.1572],
          [35.3421,  6.4070]]]]))


In [39]:
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = groups[i]
    # print(current_group.size())
    current_norm = torch.zeros(1)
    for j in range(0, 2):
        current_map_set = current_group[j]  
        print(current_map_set.shape)
        num = current_group.size(0)
        # print(num)
        sub_tensor = current_map_set.contiguous().view(num, -1)
        # print(sub_tensor.shape)
        sub_tensor_2 = current_map_set[0].view(-1,4)
        # print(sub_tensor_2.shape)
        difference_tensor = torch.sub(sub_tensor, sub_tensor_2)
        print(difference_tensor)
        num_tensor = difference_tensor.norm(1, dim=1)
        denom_tensor = torch.add(sub_tensor.norm(1, dim=1), sub_tensor_2.norm(1))
        value_tensor = torch.div(num_tensor, denom_tensor).norm(1)
        current_norm = current_norm + value_tensor
    l1_norms[i] = current_norm

torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [20.2044,  4.8905, -0.6969,  9.2941]])
torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 4.4382, 16.1910, 25.1669,  2.5293]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ 14.8858,  -7.3813, -12.8645,  22.1204]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [  7.2477, -12.3195,  26.3419, -53.6818]])


In [40]:
import random
number_of_groups = 2
maps_per_group = int(len(activations[1]) / number_of_groups)
activation_groups = torch.split(activations, maps_per_group, dim=1)
activation_groups = list(activation_groups)
input = torch.empty(2)
groupwise_activation_norms = torch.zeros_like(input).cuda()
num_random_pairs = 2

for i in range(0, 2):
    current_group = activation_groups[i]
    batch_size = current_group.shape[0]
    num_of_filters = current_group.shape[1]
    random_map_indices = random.sample(range(0, num_of_filters), num_random_pairs)
    random_map_indices = torch.LongTensor(random_map_indices)
    selected_pairs = torch.index_select(current_group, 1, random_map_indices)
    selected_pair_groups = torch.split(selected_pairs, num_random_pairs//2, dim=1)
    selected_pair_groups = list(selected_pair_groups)
    difference_tensor = torch.sub(selected_pair_groups[0], selected_pair_groups[1])
    difference_tensor = difference_tensor.contiguous().view(-1,
                                                            difference_tensor.shape[2] *
                                                            difference_tensor.shape[3])
    print(difference_tensor)
    num_tensor_norm = difference_tensor.norm(1, dim=1)
    selected_pair_groups[0] = selected_pair_groups[0].view(-1,
                                                       selected_pair_groups[0].shape[2]*
                                                       selected_pair_groups[0].shape[3])
    selected_pair_groups[1] = selected_pair_groups[1].view(-1,
                                                       selected_pair_groups[1].shape[2]*
                                                       selected_pair_groups[1].shape[3])
    
    denom_tensor_norm = torch.add(selected_pair_groups[0].norm(1, dim=1),
                             selected_pair_groups[1].norm(1, dim=1))
    
    denom_tensor_norm = torch.add(denom_tensor_norm, num_tensor_norm)
    iou_map_wise = torch.div(2 * num_tensor_norm, denom_tensor_norm)
    iou_map_wise = torch.div(iou_map_wise, num_random_pairs)
    groupwise_activation_norms[i] = torch.div(iou_map_wise.norm(1), batch_size)
    
print(groupwise_activation_norms)


tensor([[-20.2044,  -4.8905,   0.6969,  -9.2941],
        [ -4.4382, -16.1910, -25.1669,  -2.5293]])
tensor([[-28.7212,  -8.0689,  -1.3820, -15.7711],
        [ 15.6602,  -7.7763, -15.1555,   4.7117]])
tensor([0.1198, 0.1811], device='cuda:0')


In [41]:
print(sub_tensor)

tensor([[35.0414, 33.5382, 22.2364, 69.4363],
        [42.2892, 21.2186, 48.5784, 15.7545]])


In [42]:
print(denom_tensor)

tensor([320.5047, 288.0931])


In [43]:
print(num_tensor)

tensor([ 0.0000, 99.5910])


In [44]:
l1_norms

tensor([0.2723, 0.8087])

In [45]:
l1_norms

tensor([0.2723, 0.8087])

In [46]:
difference_tensor

tensor([[-28.7212,  -8.0689,  -1.3820, -15.7711],
        [ 15.6602,  -7.7763, -15.1555,   4.7117]])

In [47]:
difference_tensor.norm(1, dim=1)

tensor([53.9432, 43.3037])

### Activation regularizer across a pair of layer

In [48]:
# our first set of activations are : <activations>
#create second set of activations
inputs = torch.randn(2,2,5,5)
activations_set2 = F.conv2d(inputs,mock_filter_combined)
activations_set2.shape

torch.Size([2, 7, 3, 3])

In [49]:
print(activations.shape)

torch.Size([2, 7, 2, 2])


In [50]:
maps_per_group = int(len(activations_set2[1]) / 2)
#print(maps_per_group)
activation_groups = torch.split(activations_set2, 2, dim=1)
activation_groups = list(activation_groups)

In [51]:
activation_groups

[tensor([[[[-17.7008,  -5.8641,  23.5794],
           [ 27.1721,  28.8436,  26.9284],
           [ -9.5199,  12.0156,  -5.4923]],
 
          [[-12.1438, -10.9801,  11.9130],
           [ 21.8212,  15.5175,  45.1714],
           [  1.3837,  26.1816,   4.3394]]],
 
 
         [[[ 21.4104,  -2.6072, -24.6902],
           [  4.2356,   8.6019, -16.2357],
           [ 12.1759,  29.9097, -10.7793]],
 
          [[ 33.2310,  -4.9027, -39.5759],
           [ 20.0659,   8.0390, -38.4173],
           [ 23.6363,  19.9502, -17.5341]]]]),
 tensor([[[[-28.5190, -18.6493,  23.7312],
           [ 10.5411,  32.0266,  19.4209],
           [ -6.1077,   6.7046,  12.1338]],
 
          [[-10.0317, -14.7439,  20.7129],
           [  6.5238,  17.4036,  20.1796],
           [ 19.0229,  -6.5880,  15.1647]]],
 
 
         [[[  8.7467,  23.7068, -17.3820],
           [ -7.8498,   7.1619,   9.8824],
           [  5.4073,  12.1971,   4.6697]],
 
          [[ 19.6418,   5.8681, -28.3233],
           [  9.8211,  -2.

In [52]:
maps_per_group = int(len(activations[1]) / 2)
#print(maps_per_group)
activation_groups_layer_1 = torch.split(activations, 2, dim=1)
activation_groups_layer_1 = list(activation_groups_layer_1)

In [53]:
activation_groups_layer_1

[tensor([[[[30.5966, 30.6605],
           [24.3373, 29.2164]],
 
          [[50.8009, 35.5511],
           [23.6404, 38.5105]]],
 
 
         [[[34.4659, 35.3320],
           [49.9759, 29.8387]],
 
          [[38.9041, 51.5231],
           [75.1428, 32.3679]]]]), tensor([[[[ 4.7757, 30.9422],
           [17.7242, -0.7584]],
 
          [[19.6616, 23.5610],
           [ 4.8597, 21.3619]]],
 
 
         [[[35.0414, 33.5382],
           [22.2364, 69.4363]],
 
          [[42.2892, 21.2186],
           [48.5784, 15.7545]]]]), tensor([[[[19.6616, 23.5610],
           [ 4.8597, 21.3619]],
 
          [[48.3828, 31.6299],
           [ 6.2416, 37.1330]]],
 
 
         [[[42.2892, 21.2186],
           [48.5784, 15.7545]],
 
          [[26.6290, 28.9950],
           [63.7339, 11.0429]]]]), tensor([[[[49.5723, 32.5651],
           [19.9215, 12.8028]]],
 
 
         [[[47.9325, 20.1572],
           [35.3421,  6.4070]]]])]

In [54]:
input = torch.empty(2)
groupwise_activation_norms = torch.zeros_like(input)

In [55]:
for i in range(0, 2):
    current_group = activation_groups[i]
    current_group_layer_1 = activation_groups_layer_1[i]
    
    num = current_group.size(0) * current_group.size(1)
    size_of_map = current_group.size(2) * current_group.size(3)
    size_of_map_layer_1 = current_group_layer_1.size(2) * current_group_layer_1.size(3)
    
    map_per_row_view = current_group.contiguous().view(num, -1)       # shape: (Batches*Channels) X (Height * Width)
    first_map_row_view =  current_group_layer_1[0][0].view(-1, size_of_map_layer_1)  # shape: 1 X (Height * Width)
    
    difference_tensor = torch.sub(map_per_row_view, first_map_row_view)
    numerator_tensor = difference_tensor.norm(1, dim=1)
    denominator_tensor = torch.add(map_per_row_view.norm(1, dim=1), first_map_row_view.norm(1))
    groupwise_activation_norms[i] = torch.div(numerator_tensor, denominator_tensor).sum()

RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1

In [56]:
activation_groups[i].shape

torch.Size([2, 2, 3, 3])

In [57]:
activation_groups_layer_1[i].shape

torch.Size([2, 2, 2, 2])

In [58]:
activation_groups_layer_1[i][0][0].unsqueeze(0)

tensor([[[30.5966, 30.6605],
         [24.3373, 29.2164]]])

### Applying the activation norm across the whole batch now

In [59]:
inputs = torch.randn(3,2,5,5)
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([3, 7, 3, 3])

In [60]:
mock_filter_combined.shape

torch.Size([7, 2, 3, 3])

In [61]:
maps_per_group = int(len(activations[1]) / 2)
print(maps_per_group)
activation_groups = torch.split(activations, 2, dim=1)
activation_groups = list(activation_groups)

3


In [62]:
print(len(activation_groups))
for i in range(len(activation_groups)):
    print(activation_groups[i].shape)

4
torch.Size([3, 2, 3, 3])
torch.Size([3, 2, 3, 3])
torch.Size([3, 2, 3, 3])
torch.Size([3, 1, 3, 3])


In [63]:
# Testing for each image a neuron is chosen
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = groups[i]
    # print(current_group.size())
    current_norm = torch.zeros(1)
    for j in range(0, 2):
        current_map_set = current_group[j]  
        print(current_map_set.shape)
        num = current_group.size(0)
        # print(num)
        sub_tensor = current_map_set.contiguous().view(num, -1)
        # print(sub_tensor.shape)
        sub_tensor_2 = current_map_set[0].view(-1,4)
        # print(sub_tensor_2.shape)
        difference_tensor = torch.sub(sub_tensor, sub_tensor_2)
        print(difference_tensor)
        num_tensor = difference_tensor.norm(1, dim=1)
        denom_tensor = torch.add(sub_tensor.norm(1, dim=1), sub_tensor_2.norm(1))
        value_tensor = torch.div(num_tensor, denom_tensor).norm(1)
        current_norm = current_norm + value_tensor
    l1_norms[i] = current_norm
print(l1_norms)

torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [20.2044,  4.8905, -0.6969,  9.2941]])
torch.Size([2, 2, 2])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 4.4382, 16.1910, 25.1669,  2.5293]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [ 14.8858,  -7.3813, -12.8645,  22.1204]])
torch.Size([2, 2, 2])
tensor([[  0.0000,   0.0000,   0.0000,   0.0000],
        [  7.2477, -12.3195,  26.3419, -53.6818]])
tensor([0.2723, 0.8087])


In [64]:
## Testing for each batch a neuron is chosen
input = torch.empty(2)
l1_norms = torch.zeros_like(input)
for i in range(0, 2):
    current_group = activation_groups[i]
    batch_size = current_group.shape[0]
    first_filter_maps = current_group[:,0, :].unsqueeze(1)
    difference_tensor = torch.sub(current_group, first_filter_maps)
    difference_tensor = difference_tensor.contiguous().view(-1, 
                                                    difference_tensor.shape[2] * difference_tensor.shape[3])
    num_tensor_norm = difference_tensor.norm(1, dim=1)
    first_filter_map_view = first_filter_maps.view(first_filter_maps.shape[0], first_filter_maps.shape[1], 
                                                    first_filter_maps.shape[2] * first_filter_maps.shape[3])
    first_filter_map_norms = first_filter_map_view.norm(1, dim=2)
    current_group_view = current_group.view(current_group.shape[0], current_group.shape[1],
                                           current_group.shape[2] * current_group.shape[3])
    current_group_norms = current_group_view.norm(1, dim=2)
    denom_tensor_part = torch.add(first_filter_map_norms, current_group_norms)
    denom_tensor_part_view = denom_tensor_part.view(-1)
    denom_tensor_norm = torch.add(denom_tensor_part_view, 
                            num_tensor_norm)
    iou_map_wise = torch.div(num_tensor_norm, denom_tensor_norm)
    l1_norms[i] = torch.div(iou_map_wise.norm(1), batch_size)

print('groupwise norm', l1_norms)

groupwise norm tensor([0.2119, 0.2260])


In [65]:
current_group

tensor([[[[-67.7866, -36.9191,  -6.2290],
          [-23.5829, -13.4695,  19.0742],
          [-25.3497,  -0.2510,   7.3293]],

         [[-43.3271, -21.6196,  -9.9934],
          [ -7.0702,  -5.8806,  15.7523],
          [-22.9951,   1.1625,   7.7530]]],


        [[[  3.4329,  26.4536,  23.8332],
          [ 23.2319,  17.8439, -12.1644],
          [ 33.1252,  20.0323,  -7.3384]],

         [[ 34.4724,  14.1175,  20.4639],
          [  9.6271,   7.5668,  -4.6012],
          [ 22.5306,  -0.2863, -13.5641]]],


        [[[  9.8017, -14.3055, -13.7639],
          [ 15.8588,  10.2939, -13.9373],
          [  7.6307,  -4.1720, -16.0641]],

         [[  0.1219, -11.6931, -13.4266],
          [  4.0194,  -1.0104, -12.8587],
          [  9.6970, -15.2968, -18.2286]]]])

In [66]:
# a = torch.Tensor(2,2,3,3)
# print('a:', a)
# b = a[:,0,:,:].unsqueeze(1)
# print('shape of b:', b.shape)
# print('b:', b)
# c = torch.sub(b, a)

# print('c shape:', c.shape)
# print('c:', c[:,0,:,:])

In [67]:
a = torch.Tensor([2,3,4])
c = a.norm(1)

In [68]:
activation_groups[2].shape

torch.Size([3, 2, 3, 3])

In [69]:
current_group = torch.stack(activation_groups[:2], dim=0)
current_group.shape
first_filter_maps = current_group[:,:, 0, :, :].unsqueeze(2)
first_filter_maps.shape

torch.Size([2, 3, 1, 3, 3])

### Comparing two neurons from different group and same groups:

In [70]:
def purely_diff_based_measure(unit_x, unit_y, feature_maps):
    
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-70-5622b700027a>, line 4)

In [71]:
mock_filter_combined.shape

torch.Size([7, 2, 3, 3])

In [72]:
inputs = torch.randn(2,2,4,4)

In [73]:
inputs

tensor([[[[-2.5040e-01, -4.4165e-01,  1.4327e-03,  2.1075e+00],
          [-2.3981e-01,  1.8919e-01,  1.7837e+00, -1.4799e+00],
          [ 5.8161e-01,  1.2003e+00, -1.7110e+00, -2.2401e+00],
          [ 8.5365e-01,  1.6133e+00, -1.2795e+00,  6.5067e-01]],

         [[ 1.4395e+00,  8.0146e-01,  9.5984e-01,  1.0663e-01],
          [-1.9015e+00, -2.8028e-01,  1.0168e+00,  4.1139e-01],
          [ 4.2417e-01, -9.0444e-01,  1.7127e+00,  2.9496e-01],
          [ 3.1056e-01, -3.4820e-01, -1.1773e+00, -8.3922e-01]]],


        [[[ 2.1817e+00, -1.1511e+00,  5.6999e-01, -8.4488e-01],
          [ 1.0534e+00, -3.3193e-01, -2.2796e+00, -2.9017e-02],
          [-1.2312e+00, -1.8102e+00,  1.6412e+00, -4.6015e-02],
          [-1.7093e+00, -6.1592e-01, -2.5223e-01,  6.7079e-01]],

         [[ 1.9713e-01,  1.4443e+00, -8.5217e-01,  3.4045e-01],
          [ 4.4652e-01, -2.7655e+00,  5.9683e-01, -1.8310e-01],
          [ 1.3856e+00, -1.6020e+00, -1.5165e+00, -1.7883e+00],
          [ 1.9327e+00,  4.7155e

In [74]:
activations = F.conv2d(inputs,mock_filter_combined)
activations.shape

torch.Size([2, 7, 2, 2])

In [75]:
activations

tensor([[[[ 20.3447,  -3.6006],
          [ -0.1327, -15.8012]],

         [[ 27.2259,  27.0315],
          [ 14.4511, -13.8277]],

         [[ 13.3662,   2.1523],
          [ 26.7683,  -6.2244]],

         [[ 24.8469,  18.0259],
          [ 15.8077, -24.5976]],

         [[ 24.8469,  18.0259],
          [ 15.8077, -24.5976]],

         [[  9.7275,  21.4245],
          [ -0.2310, -10.9674]],

         [[ 31.4743,   8.4767],
          [  3.8633, -10.3287]]],


        [[[-37.0816, -49.0371],
          [-16.9035,  -7.6240]],

         [[-54.8978, -51.6846],
          [-57.0522, -11.3033]],

         [[-17.4338, -53.6368],
          [ -6.7704, -41.0864]],

         [[-37.9405, -12.0334],
          [-22.2386, -20.6954]],

         [[-37.9405, -12.0334],
          [-22.2386, -20.6954]],

         [[-32.7216, -39.6424],
          [-35.6666,  -1.4720]],

         [[ -8.8883, -21.9993],
          [-25.6879, -20.9507]]]])

In [76]:
std_map_wise

NameError: name 'std_map_wise' is not defined

In [77]:
activations[:,4]

tensor([[[ 24.8469,  18.0259],
         [ 15.8077, -24.5976]],

        [[-37.9405, -12.0334],
         [-22.2386, -20.6954]]])

In [78]:
unit_x = 0
unit_y = 1
act_unit_x = activations[:, unit_x]
act_unit_y = activations[:, unit_y]

In [79]:
act_unit_x

tensor([[[ 20.3447,  -3.6006],
         [ -0.1327, -15.8012]],

        [[-37.0816, -49.0371],
         [-16.9035,  -7.6240]]])

In [80]:
act_unit_y

tensor([[[ 27.2259,  27.0315],
         [ 14.4511, -13.8277]],

        [[-54.8978, -51.6846],
         [-57.0522, -11.3033]]])

In [81]:
act_unit_y.shape

torch.Size([2, 2, 2])

In [82]:
number_of_maps = activations.size(1)

In [83]:
number_of_maps

7

In [84]:
std_map_wise = activations.transpose(0, 1).contiguous().view(number_of_maps, -1).std(1)

In [85]:
std_map_wise.shape

torch.Size([7])

In [86]:
activations

tensor([[[[ 20.3447,  -3.6006],
          [ -0.1327, -15.8012]],

         [[ 27.2259,  27.0315],
          [ 14.4511, -13.8277]],

         [[ 13.3662,   2.1523],
          [ 26.7683,  -6.2244]],

         [[ 24.8469,  18.0259],
          [ 15.8077, -24.5976]],

         [[ 24.8469,  18.0259],
          [ 15.8077, -24.5976]],

         [[  9.7275,  21.4245],
          [ -0.2310, -10.9674]],

         [[ 31.4743,   8.4767],
          [  3.8633, -10.3287]]],


        [[[-37.0816, -49.0371],
          [-16.9035,  -7.6240]],

         [[-54.8978, -51.6846],
          [-57.0522, -11.3033]],

         [[-17.4338, -53.6368],
          [ -6.7704, -41.0864]],

         [[-37.9405, -12.0334],
          [-22.2386, -20.6954]],

         [[-37.9405, -12.0334],
          [-22.2386, -20.6954]],

         [[-32.7216, -39.6424],
          [-35.6666,  -1.4720]],

         [[ -8.8883, -21.9993],
          [-25.6879, -20.9507]]]])

In [87]:
receptive_fields = activations.transpose(1, 3).div(std_map_wise).transpose(1, 3)

In [88]:
receptive_fields.shape

torch.Size([2, 7, 2, 2])

In [89]:
receptive_fields

tensor([[[[ 0.9381, -0.1660],
          [-0.0061, -0.7286]],

         [[ 0.7535,  0.7482],
          [ 0.4000, -0.3827]],

         [[ 0.5004,  0.0806],
          [ 1.0021, -0.2330]],

         [[ 1.0565,  0.7665],
          [ 0.6721, -1.0459]],

         [[ 1.0565,  0.7665],
          [ 0.6721, -1.0459]],

         [[ 0.4297,  0.9463],
          [-0.0102, -0.4844]],

         [[ 1.6320,  0.4395],
          [ 0.2003, -0.5356]]],


        [[[-1.7099, -2.2612],
          [-0.7795, -0.3516]],

         [[-1.5194, -1.4305],
          [-1.5790, -0.3128]],

         [[-0.6526, -2.0079],
          [-0.2535, -1.5381]],

         [[-1.6132, -0.5117],
          [-0.9456, -0.8800]],

         [[-1.6132, -0.5117],
          [-0.9456, -0.8800]],

         [[-1.4453, -1.7510],
          [-1.5754, -0.0650]],

         [[-0.4609, -1.1407],
          [-1.3320, -1.0864]]]])

In [90]:
receptive_fields = torch.sigmoid(receptive_fields)

In [91]:
receptive_fields

tensor([[[[0.7187, 0.4586],
          [0.4985, 0.3255]],

         [[0.6799, 0.6788],
          [0.5987, 0.4055]],

         [[0.6225, 0.5201],
          [0.7315, 0.4420]],

         [[0.7420, 0.6828],
          [0.6620, 0.2600]],

         [[0.7420, 0.6828],
          [0.6620, 0.2600]],

         [[0.6058, 0.7204],
          [0.4974, 0.3812]],

         [[0.8364, 0.6082],
          [0.5499, 0.3692]]],


        [[[0.1532, 0.0944],
          [0.3144, 0.4130]],

         [[0.1795, 0.1930],
          [0.1709, 0.4224]],

         [[0.3424, 0.1184],
          [0.4370, 0.1768]],

         [[0.1661, 0.3748],
          [0.2798, 0.2932]],

         [[0.1661, 0.3748],
          [0.2798, 0.2932]],

         [[0.1907, 0.1479],
          [0.1715, 0.4838]],

         [[0.3868, 0.2422],
          [0.2088, 0.2523]]]])

In [92]:
unit_x = 0
unit_y = 1
act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]

In [93]:
act_unit_y.shape

torch.Size([2, 2, 2])

In [94]:
act_unit_x

tensor([[[0.7187, 0.4586],
         [0.4985, 0.3255]],

        [[0.1532, 0.0944],
         [0.3144, 0.4130]]])

In [95]:
act_unit_y

tensor([[[0.6799, 0.6788],
         [0.5987, 0.4055]],

        [[0.1795, 0.1930],
         [0.1709, 0.4224]]])

In [96]:
difference_tensor = act_unit_x - act_unit_y

In [97]:
hadamard_prod = torch.mul(act_unit_x, act_unit_y)

In [98]:
hadamard_prod

tensor([[[0.4887, 0.3113],
         [0.2984, 0.1320]],

        [[0.0275, 0.0182],
         [0.0537, 0.1745]]])

In [99]:
difference_tensor

tensor([[[ 0.0388, -0.2202],
         [-0.1002, -0.0800]],

        [[-0.0264, -0.0986],
         [ 0.1435, -0.0094]]])

In [100]:
difference_tensor.norm(1)

tensor(0.7171)

In [101]:
hadamard_prod.norm(1)

tensor(1.5043)

In [102]:
score = (2 * difference_tensor.norm(1)) / (act_unit_x.norm(1) + act_unit_y.norm(1) + difference_tensor.norm(1))

In [103]:
score

tensor(0.2042)

In [104]:
unit_x = 2
unit_y = 3
act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]
difference_tensor = act_unit_x - act_unit_y
hadamard_prod = torch.mul(act_unit_x, act_unit_y)
print(difference_tensor)

tensor([[[-0.1195, -0.1626],
         [ 0.0695,  0.1820]],

        [[ 0.1763, -0.2564],
         [ 0.1572, -0.1164]]])


In [105]:
difference_tensor.norm(1)

tensor(1.2398)

In [106]:
hadamard_prod

tensor([[[0.4619, 0.3551],
         [0.4842, 0.1149]],

        [[0.0569, 0.0444],
         [0.1223, 0.0518]]])

In [107]:
score = (2 * difference_tensor.norm(1)) / (act_unit_x.norm(1) + act_unit_y.norm(1) + difference_tensor.norm(1))

In [108]:
score

tensor(0.3065)

In [109]:
receptive_fields.shape

torch.Size([2, 7, 2, 2])

In [110]:
unit_x = np.array([0 ,2])
unit_y = np.array([1 ,3])

act_unit_x = receptive_fields[:, unit_x]
act_unit_y = receptive_fields[:, unit_y]

In [111]:
act_unit_x[:,0]

tensor([[[0.7187, 0.4586],
         [0.4985, 0.3255]],

        [[0.1532, 0.0944],
         [0.3144, 0.4130]]])

In [112]:
act_unit_y[:,0]

tensor([[[0.6799, 0.6788],
         [0.5987, 0.4055]],

        [[0.1795, 0.1930],
         [0.1709, 0.4224]]])

In [113]:
difference_tensor = act_unit_x - act_unit_y

In [114]:
difference_tensor[:, 0]

tensor([[[ 0.0388, -0.2202],
         [-0.1002, -0.0800]],

        [[-0.0264, -0.0986],
         [ 0.1435, -0.0094]]])

In [115]:
difference_tensor[:, 1]

tensor([[[-0.1195, -0.1626],
         [ 0.0695,  0.1820]],

        [[ 0.1763, -0.2564],
         [ 0.1572, -0.1164]]])

In [116]:
hadamard_tensor = torch.mul(act_unit_x, act_unit_y)

In [117]:
hadamard_tensor[:,0]

tensor([[[0.4887, 0.3113],
         [0.2984, 0.1320]],

        [[0.0275, 0.0182],
         [0.0537, 0.1745]]])

In [118]:
score = []
for i in range(len(unit_x)):
    score.append((2 * difference_tensor[:,i].norm(1)) 
                 / (act_unit_x[:, i].norm(1) + act_unit_y[:, i].norm(1) + difference_tensor[:,i].norm(1)))

In [119]:
difference_tensor.shape

torch.Size([2, 2, 2, 2])

In [120]:
torch.stack(score)

tensor([0.2042, 0.3065])

In [121]:
score

[tensor(0.2042), tensor(0.3065)]

### R3 Activation Norm Spatially concentrate the activations

In [338]:
inputs = torch.randn(2,2,5,5)
activations = F.conv2d(inputs,mock_filter_combined)
print(activations.shape)
batch_size = activations.shape[0]

torch.Size([2, 7, 3, 3])


In [334]:
batch_size

2

In [250]:
indices = np.indices((activations.shape[2], activations.shape[3]))

In [331]:
indices = torch.Tensor(indices)
print(indices.shape)

torch.Size([2, 3, 3])


In [252]:
x_coordinates = indices[1]
y_coordinates = indices[0]

In [253]:
x_coordinates

tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])

In [254]:
y_coordinates

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [332]:
activation_sums = torch.sum(activations,(2,3))
print(activation_sums.size())
activation_sums = activation_sums.view(-1)
activation_sums.size()

torch.Size([2, 7])


torch.Size([14])

In [256]:
x_centers = torch.mul(x_coordinates, activations)

In [302]:
x_centers = torch.sum(x_centers, (2,3))

In [303]:
x_centers = x_centers.view(-1)
x_centers = torch.div(x_centers, activation_sums)
x_centers.size()

torch.Size([14])

In [304]:
y_centers = torch.mul(y_coordinates, activations)
y_centers = torch.sum(y_centers, (2,3))
y_centers = y_centers.view(-1)
y_centers = torch.div(y_centers, activation_sums)
y_centers.size()

torch.Size([14])

In [305]:
x_centers.unsqueeze_(1).unsqueeze_(1)
x_coordinates_expand = x_coordinates.expand(14,3,3)
print(x_coordinates_expand.shape)
print(x_centers.shape)

torch.Size([14, 3, 3])
torch.Size([14, 1, 1])


In [308]:
y_centers.unsqueeze_(1).unsqueeze_(1)
y_coordinates_expand = y_coordinates.expand(14,3,3)
print(y_coordinates_expand.shape)
print(y_centers.shape)

torch.Size([14, 3, 3])
torch.Size([14, 1, 1])


In [320]:
x_deviations = torch.sub(x_coordinates_expand,x_centers)
x_deviations = torch.pow(x_deviations, 2)
print(x_deviations.shape)

y_deviations = torch.sub(y_coordinates_expand, y_centers)
y_deviations = torch.pow(y_deviations, 2)
print(y_deviations.shape)

torch.Size([14, 3, 3])
torch.Size([14, 3, 3])


In [322]:
num_part_1 = torch.pow(torch.add(x_deviations, y_deviations), 0.5)
num_part_1.shape

torch.Size([14, 3, 3])

In [317]:
activations = activations.view(-1,activations.shape[2],activations.shape[3])
activations.shape

torch.Size([14, 3, 3])

In [323]:
num = torch.mul(activations, num_part_1)
num.shape

torch.Size([14, 3, 3])

In [325]:
num = torch.sum(num,(1,2))
num.shape

torch.Size([14])

In [330]:
score = torch.div(num, activation_sums)
score = torch.div(score.sum(), batch_size)
score 

tensor(-1.3242)

In [339]:
# whole function at once activations pf size N x C x F_l x F_l
batch_size = activations.shape[0] 
indices = np.indices((activations.shape[2], activations.shape[3])) #2 x F_l x F_l
indices = torch.Tensor(indices)
x_coordinates = indices[1]          # F_l x F_l
y_coordinates = indices[0]          # F_l x F_l
activation_sums = torch.sum(activations,(2,3))       # N x C
activation_sums = activation_sums.view(-1)           # N * C

x_centers = torch.mul(x_coordinates, activations)    # N x C x F_l x F_l 
x_centers = torch.sum(x_centers, (2,3))              # N x C
x_centers = x_centers.view(-1)                       # N*C
x_centers = torch.div(x_centers, activation_sums)    # N*C

y_centers = torch.mul(y_coordinates, activations)
y_centers = torch.sum(y_centers, (2,3))
y_centers = y_centers.view(-1)
y_centers = torch.div(y_centers, activation_sums)    # N*C

x_centers.unsqueeze_(1).unsqueeze_(1)
x_coordinates_expand = x_coordinates.expand(14,3,3)
y_centers.unsqueeze_(1).unsqueeze_(1)
y_coordinates_expand = y_coordinates.expand(14,3,3)

x_deviations = torch.sub(x_coordinates_expand,x_centers)
x_deviations = torch.pow(x_deviations, 2)
y_deviations = torch.sub(y_coordinates_expand, y_centers)
y_deviations = torch.pow(y_deviations, 2)                 # N*C x F_l x F_l

num_part_1 = torch.pow(torch.add(x_deviations, y_deviations), 0.5)
activations = activations.view(-1,activations.shape[2],activations.shape[3]) # N*C x F_l x F_l
num = torch.mul(activations, num_part_1)
num = torch.sum(num,(1,2))     # N*C       
score = torch.div(num, activation_sums)
score = torch.div(score.sum(), batch_size)   # 1


In [340]:
score

tensor(2.2960)

In [341]:
activation_sums

tensor([-58.5977, -53.1712, -29.2761, -15.2708, -15.2708, -49.5474,  -7.5840,
         53.8446,  30.4071, 120.9402,  23.1874,  23.1874,  30.7302, -33.4064])

In [342]:
activation_sums + 1

tensor([-57.5977, -52.1712, -28.2761, -14.2708, -14.2708, -48.5474,  -6.5840,
         54.8446,  31.4071, 121.9402,  24.1874,  24.1874,  31.7302, -32.4064])